### PR TITLE
Update to 0.3.6

### PR DESCRIPTION
**Pull request by glandium**
And remove RUSTC_BOOTSTRAP.

### CODE REVIEW

**Comment by glandium** [comment]
With this, I was able to update Firefox to encoding_rs 0.8.29.

**Comment by hsivonen** [comment]
rs+ based on "With this, I was able to update Firefox to encoding_rs 0.8.29.", but this shows up as having a merge conflict. Should I just import the branch from the command line?

**Comment by glandium** [comment]
Do you mean github's merge tells you there's a conflict? If so, yeah, you should probably just fetch the `refs/pull/5/head` ref and push that to some branch. That being said, I'm going to update, because there is actually an error in the merge.

**Comment by glandium** [comment]
8d3eafcb5c28551d1d0f6bbc13970779cd0cb79b is good.

**Comment by hsivonen** [comment]
> [8d3eafc](https://github.com/hsivonen/packed_simd/commit/8d3eafcb5c28551d1d0f6bbc13970779cd0cb79b) is good.

This is now the [branch 0_3_6](https://github.com/hsivonen/packed_simd/tree/0_3_6). Thanks.

**Comment by hsivonen** [comment]
This looks obsolete now.

**Pull request closed without merging**
