### PR TITLE
Lower MSRV by restoring the old non-const generics code on < 1.54

### PR DESCRIPTION
**Pull request by glandium**
Use rustc_version 0.2 rather than the latest version because that's
what's already vendored in mozilla-central.

### CODE REVIEW

**Comment by hsivonen** [comment]
Thanks. Pulled and pushed from command line into a [different branch](https://github.com/hsivonen/packed_simd/tree/rust_1_54_esr) in order to avoid potential future conflicts on mozilla-central after the current ESR is no longer even supported.

Not sure how to make the GitHub PR status reflect this. Sorry.

**Comment by hsivonen** [comment]
This doesn't actually compile with 1.54 beta for me.

**Comment by glandium** [comment]
> This doesn't actually compile with 1.54 beta for me.

It worked with the 1.54.0 nighty I had... the following fixes it:
```
diff --git a/build.rs b/build.rs
index 0596da5..4a1b336 100644
--- a/build.rs
+++ b/build.rs
@@ -8,7 +8,7 @@ fn main() {
         println!("cargo:rustc-cfg=libcore_neon");
     }
     let ver = version().unwrap();
-    if ver >= Version::parse("1.54.0").unwrap() {
+    if ver >= Version::parse("1.54.0-alpha").unwrap() {
         println!("cargo:rustc-cfg=use_const_generics");
     }
 }
```

> in order to avoid potential future conflicts on mozilla-central after the current ESR is no longer even supported.

You could just revert this when that happens.

**Comment by hsivonen** [comment]
> the following fixes it:

Thanks.

> You could just revert this when that happens.

I think it doesn't make sense to take code that's irrelevant to central and ESR91 to central with the plan to revert. I'd rather take a different patch in ESR78 and central and not worry about reverting once ESR78 is obsolete but ESR91 and central remain maintained.

**Pull request closed without merging**
